In [1]:
import sqlite3
import pandas as pd
import numpy as np
import os
import datetime
import itertools as it
from math import pi
from datetime import datetime
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Create a SQL connection to our SQLite database
conn = sqlite3.connect("database/database.sqlite")

cur = conn.cursor()

In [3]:
tables = pd.read_sql("""SELECT NAME
                       FROM sqlite_master
                       where type='table';""",conn)
print(tables)

                name
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

In [4]:
query1 = """SELECT * FROM Player_Attributes;"""
player_attributes = pd.read_sql(query1,conn)
print(player_attributes)

            id  player_fifa_api_id  player_api_id                 date  \
0            1              218353         505942  2016-02-18 00:00:00
1            2              218353         505942  2015-11-19 00:00:00
2            3              218353         505942  2015-09-21 00:00:00
3            4              218353         505942  2015-03-20 00:00:00
4            5              218353         505942  2007-02-22 00:00:00
...        ...                 ...            ...                  ...
183973  183974              102359          39902  2009-08-30 00:00:00
183974  183975              102359          39902  2009-02-22 00:00:00
183975  183976              102359          39902  2008-08-30 00:00:00
183976  183977              102359          39902  2007-08-30 00:00:00
183977  183978              102359          39902  2007-02-22 00:00:00

        overall_rating  potential preferred_foot attacking_work_rate  \
0                 67.0       71.0          right              medium
1                 67.0       71.0          right              medium
2                 62.0       66.0          right              medium
3                 61.0       65.0          right              medium
4                 61.0       65.0          right              medium
...                ...        ...            ...                 ...
183973            83.0       85.0          right              medium
183974            78.0       80.0          right              medium
183975            77.0       80.0          right              medium
183976            78.0       81.0          right              medium
183977            80.0       81.0          right              medium

       defensive_work_rate  crossing  ...  vision  penalties  marking  \
0                   medium      49.0  ...    54.0       48.0     65.0
1                   medium      49.0  ...    54.0       48.0     65.0
2                   medium      49.0  ...    54.0       48.0     65.0
3                   medium      48.0  ...    53.0       47.0     62.0
4                   medium      48.0  ...    53.0       47.0     62.0
...                    ...       ...  ...     ...        ...      ...
183973                 low      84.0  ...    88.0       83.0     22.0
183974                 low      74.0  ...    88.0       70.0     32.0
183975                 low      74.0  ...    88.0       70.0     32.0
183976                 low      74.0  ...    88.0       53.0     28.0
183977                 low      74.0  ...    88.0       53.0     38.0

        standing_tackle  sliding_tackle  gk_diving  gk_handling  gk_kicking  \
0                  69.0            69.0        6.0         11.0        10.0
1                  69.0            69.0        6.0         11.0        10.0
2                  66.0            69.0        6.0         11.0        10.0
3                  63.0            66.0        5.0         10.0         9.0
4                  63.0            66.0        5.0         10.0         9.0
...                 ...             ...        ...          ...         ...
183973             31.0            30.0        9.0         20.0        84.0
183974             31.0            30.0        9.0         20.0        73.0
183975             31.0            30.0        9.0         20.0        73.0
183976             32.0            30.0        9.0         20.0        73.0
183977             32.0            30.0        9.0          9.0        78.0

        gk_positioning  gk_reflexes
0                  8.0          8.0
1                  8.0          8.0
2                  8.0          8.0
3                  7.0          7.0
4                  7.0          7.0
...                ...          ...
183973            20.0         20.0
183974            20.0         20.0
183975            20.0         20.0
183976            20.0         20.0
183977             7.0         15.0

[183978 rows x 42 columns]

In [5]:
query2 = """SELECT * FROM Player"""
player_data = pd.read_sql(query2,conn)
print(player_data)

          id  player_api_id          player_name  player_fifa_api_id  \
0          1         505942   Aaron Appindangoye              218353
1          2         155782      Aaron Cresswell              189615
2          3         162549          Aaron Doran              186170
3          4          30572        Aaron Galindo              140161
4          5          23780         Aaron Hughes               17725
...      ...            ...                  ...                 ...
11055  11071          26357       Zoumana Camara                2488
11056  11072         111182         Zsolt Laczko              164680
11057  11073          36491            Zsolt Low              111191
11058  11074          35506  Zurab Khizanishvili               47058
11059  11075          39902   Zvjezdan Misimovic              102359

                  birthday  height  weight
0      1992-02-29 00:00:00  182.88     187
1      1989-12-15 00:00:00  170.18     146
2      1991-05-13 00:00:00  170.18     163
3      1982-05-08 00:00:00  182.88     198
4      1979-11-08 00:00:00  182.88     154
...                    ...     ...     ...
11055  1979-04-03 00:00:00  182.88     168
11056  1986-12-18 00:00:00  182.88     176
11057  1979-04-29 00:00:00  180.34     154
11058  1981-10-06 00:00:00  185.42     172
11059  1982-06-05 00:00:00  180.34     176

[11060 rows x 7 columns]

In [6]:
query3 = """SELECT * FROM Team"""
team_data = pd.read_sql(query3,conn)
print(team_data)

        id  team_api_id  team_fifa_api_id      team_long_name team_short_name
0        1         9987             673.0            KRC Genk             GEN
1        2         9993             675.0        Beerschot AC             BAC
2        3        10000           15005.0    SV Zulte-Waregem             ZUL
3        4         9994            2007.0    Sporting Lokeren             LOK
4        5         9984            1750.0   KSV Cercle Brugge             CEB
..     ...          ...               ...                 ...             ...
294  49479        10190             898.0       FC St. Gallen             GAL
295  49837        10191            1715.0             FC Thun             THU
296  50201         9777             324.0         Servette FC             SER
297  50204         7730            1862.0  FC Lausanne-Sports             LAU
298  51606         7896               NaN              Lugano             LUG

[299 rows x 5 columns]

In [7]:
query4 = """SELECT * FROM Team_Attributes"""
team_attributes = pd.read_sql(query4,conn)
print(team_attributes)

        id  team_fifa_api_id  team_api_id                 date  \
0        1               434         9930  2010-02-22 00:00:00
1        2               434         9930  2014-09-19 00:00:00
2        3               434         9930  2015-09-10 00:00:00
3        4                77         8485  2010-02-22 00:00:00
4        5                77         8485  2011-02-22 00:00:00
...    ...               ...          ...                  ...
1453  1454             15005        10000  2011-02-22 00:00:00
1454  1455             15005        10000  2012-02-22 00:00:00
1455  1456             15005        10000  2013-09-20 00:00:00
1456  1457             15005        10000  2014-09-19 00:00:00
1457  1458             15005        10000  2015-09-10 00:00:00

      buildUpPlaySpeed buildUpPlaySpeedClass  buildUpPlayDribbling  \
0                   60              Balanced                   NaN
1                   52              Balanced                  48.0
2                   47              Balanced                  41.0
3                   70                  Fast                   NaN
4                   47              Balanced                   NaN
...                ...                   ...                   ...
1453                52              Balanced                   NaN
1454                54              Balanced                   NaN
1455                54              Balanced                   NaN
1456                54              Balanced                  42.0
1457                54              Balanced                  42.0

     buildUpPlayDribblingClass  buildUpPlayPassing buildUpPlayPassingClass  \
0                       Little                  50                   Mixed
1                       Normal                  56                   Mixed
2                       Normal                  54                   Mixed
3                       Little                  70                    Long
4                       Little                  52                   Mixed
...                        ...                 ...                     ...
1453                    Little                  52                   Mixed
1454                    Little                  51                   Mixed
1455                    Little                  51                   Mixed
1456                    Normal                  51                   Mixed
1457                    Normal                  51                   Mixed

      ... chanceCreationShooting  chanceCreationShootingClass  \
0     ...                     55                       Normal
1     ...                     64                       Normal
2     ...                     64                       Normal
3     ...                     70                         Lots
4     ...                     52                       Normal
...   ...                    ...                          ...
1453  ...                     53                       Normal
1454  ...                     50                       Normal
1455  ...                     32                       Little
1456  ...                     32                       Little
1457  ...                     32                       Little

     chanceCreationPositioningClass  defencePressure defencePressureClass  \
0                         Organised               50               Medium
1                         Organised               47               Medium
2                         Organised               47               Medium
3                         Organised               60               Medium
4                         Organised               47               Medium
...                             ...              ...                  ...
1453                      Organised               46               Medium
1454                      Organised               44               Medium
1455                      Organised               44               Medium
1456                      Organised               44               Medium
1457                      Organised               44               Medium

      defenceAggression defenceAggressionClass defenceTeamWidth  \
0                    55                  Press               45
1                    44                  Press               54
2                    44                  Press               54
3                    70                 Double               70
4                    47                  Press               52
...                 ...                    ...              ...
1453                 48                  Press               53
1454                 55                  Press               53
1455                 58                  Press               37
1456                 58                  Press               37
1457                 58                  Press               37

      defenceTeamWidthClass defenceDefenderLineClass
0                    Normal                    Cover
1                    Normal                    Cover
2                    Normal                    Cover
3                      Wide                    Cover
4                    Normal                    Cover
...                     ...                      ...
1453                 Normal                    Cover
1454                 Normal                    Cover
1455                 Normal                    Cover
1456                 Normal                    Cover
1457                 Normal                    Cover

[1458 rows x 25 columns]

In [8]:
df = pd.merge(player_attributes, player_data, on="player_api_id", how="inner")

In [9]:
df

,id_x,player_fifa_api_id_x,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,player_name,player_fifa_api_id_y,birthday,height,weight
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,11.0,10.0,8.0,8.0,1,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,11.0,10.0,8.0,8.0,1,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,11.0,10.0,8.0,8.0,1,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,10.0,9.0,7.0,7.0,1,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,10.0,9.0,7.0,7.0,1,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183974,102359,39902,2009-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,...,20.0,84.0,20.0,20.0,11075,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176
183974,183975,102359,39902,2009-02-22 00:00:00,78.0,80.0,right,medium,low,74.0,...,20.0,73.0,20.0,20.0,11075,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176
183975,183976,102359,39902,2008-08-30 00:00:00,77.0,80.0,right,medium,low,74.0,...,20.0,73.0,20.0,20.0,11075,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176
183976,183977,102359,39902,2007-08-30 00:00:00,78.0,81.0,right,medium,low,74.0,...,20.0,73.0,20.0,20.0,11075,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176
183977,183978,102359,39902,2007-02-22 00:00:00,80.0,81.0,right,medium,low,74.0,...,9.0,78.0,7.0,15.0,11075,Zvjezdan Misimovic,102359,1982-06-05 00:00:00,180.34,176

In [93]:
Ronaldo = df.loc[df['player_name'] == "Cristiano Ronaldo"]
Ronaldo

,id_x,player_fifa_api_id_x,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,player_name,player_fifa_api_id_y,birthday,height,weight
33330,33331,20801,30893,2015-10-16 00:00:00,93.0,93.0,right,high,low,82.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33331,33332,20801,30893,2015-09-25 00:00:00,93.0,93.0,right,high,low,82.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33332,33333,20801,30893,2015-09-21 00:00:00,93.0,93.0,right,high,low,82.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33333,33334,20801,30893,2015-05-15 00:00:00,92.0,92.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33334,33335,20801,30893,2015-04-17 00:00:00,92.0,92.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33335,33336,20801,30893,2014-10-31 00:00:00,92.0,92.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33336,33337,20801,30893,2014-09-18 00:00:00,92.0,92.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33337,33338,20801,30893,2014-02-07 00:00:00,92.0,92.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33338,33339,20801,30893,2014-01-17 00:00:00,92.0,95.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33339,33340,20801,30893,2013-09-20 00:00:00,92.0,95.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33340,33341,20801,30893,2013-03-22 00:00:00,92.0,95.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33341,33342,20801,30893,2013-03-08 00:00:00,92.0,95.0,right,high,low,83.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33342,33343,20801,30893,2013-03-01 00:00:00,92.0,94.0,right,high,low,84.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33343,33344,20801,30893,2013-02-15 00:00:00,92.0,94.0,right,high,low,84.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33344,33345,20801,30893,2012-08-31 00:00:00,92.0,94.0,right,high,low,84.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33345,33346,20801,30893,2012-02-22 00:00:00,92.0,94.0,right,high,low,84.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33346,33347,20801,30893,2011-08-30 00:00:00,92.0,94.0,right,high,low,84.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33347,33348,20801,30893,2011-02-22 00:00:00,89.0,93.0,right,high,low,84.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33348,33349,20801,30893,2010-08-30 00:00:00,89.0,94.0,right,high,low,84.0,...,11.0,15.0,14.0,11.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33349,33350,20801,30893,2010-02-22 00:00:00,89.0,93.0,right,high,low,84.0,...,21.0,71.0,21.0,21.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33350,33351,20801,30893,2009-08-30 00:00:00,89.0,94.0,right,high,low,86.0,...,21.0,71.0,21.0,21.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33351,33352,20801,30893,2009-02-22 00:00:00,90.0,94.0,right,high,low,89.0,...,21.0,71.0,21.0,21.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33352,33353,20801,30893,2008-08-30 00:00:00,91.0,94.0,right,high,low,89.0,...,21.0,72.0,21.0,21.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33353,33354,20801,30893,2007-08-30 00:00:00,91.0,94.0,right,high,low,88.0,...,21.0,73.0,21.0,21.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176
33354,33355,20801,30893,2007-02-22 00:00:00,87.0,92.0,right,high,low,80.0,...,10.0,68.0,8.0,5.0,1995,Cristiano Ronaldo,20801,1985-02-05 00:00:00,185.42,176

In [11]:
Ramos = df.loc[df['player_name'] == "Sergio Ramos"]

In [12]:
Azpilicueta = df.loc[df['player_name'] == "Cesar Azpilicueta"]

In [13]:
Torres = df.loc[df['player_name'] == "Fernando Torres"]

In [14]:
DiMaria = df.loc[df['player_name'] == "Angel Di Maria"]

In [15]:
Ibrahimovic = df.loc[df['player_name'] == "Zlatan Ibrahimovic"]

In [16]:
Beckham = df.loc[df['player_name'] == "David Beckham"]

In [94]:
Messi = df.loc[df['player_name'] == "Lionel Messi"]
Messi

,id_x,player_fifa_api_id_x,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,player_name,player_fifa_api_id_y,birthday,height,weight
102482,102483,158023,30981,2015-12-17 00:00:00,94.0,94.0,left,medium,low,80.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102483,102484,158023,30981,2015-10-16 00:00:00,94.0,94.0,left,medium,low,80.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102484,102485,158023,30981,2015-09-21 00:00:00,94.0,95.0,left,medium,low,80.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102485,102486,158023,30981,2015-06-26 00:00:00,93.0,93.0,left,medium,low,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102486,102487,158023,30981,2015-03-13 00:00:00,93.0,95.0,left,medium,low,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102487,102488,158023,30981,2015-02-20 00:00:00,93.0,95.0,left,medium,low,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102488,102489,158023,30981,2015-01-23 00:00:00,93.0,95.0,left,medium,low,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102489,102490,158023,30981,2014-10-17 00:00:00,93.0,95.0,left,medium,low,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102490,102491,158023,30981,2014-09-18 00:00:00,93.0,95.0,left,medium,low,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102491,102492,158023,30981,2014-04-25 00:00:00,94.0,97.0,left,medium,low,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102492,102493,158023,30981,2013-11-15 00:00:00,94.0,97.0,left,high,medium,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102493,102494,158023,30981,2013-09-20 00:00:00,94.0,97.0,left,high,medium,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102494,102495,158023,30981,2013-03-22 00:00:00,94.0,97.0,left,high,medium,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102495,102496,158023,30981,2013-03-08 00:00:00,94.0,97.0,left,high,medium,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102496,102497,158023,30981,2013-02-15 00:00:00,94.0,97.0,left,high,medium,84.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102497,102498,158023,30981,2012-08-31 00:00:00,94.0,96.0,left,high,medium,85.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102498,102499,158023,30981,2012-02-22 00:00:00,94.0,96.0,left,high,medium,85.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102499,102500,158023,30981,2011-08-30 00:00:00,94.0,96.0,left,high,medium,85.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102500,102501,158023,30981,2011-02-22 00:00:00,90.0,94.0,left,high,medium,85.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102501,102502,158023,30981,2010-08-30 00:00:00,90.0,95.0,left,high,medium,85.0,...,11.0,15.0,14.0,8.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102502,102503,158023,30981,2010-02-22 00:00:00,90.0,94.0,left,high,medium,82.0,...,20.0,75.0,20.0,20.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102503,102504,158023,30981,2009-08-30 00:00:00,90.0,95.0,left,high,medium,82.0,...,20.0,75.0,20.0,20.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102504,102505,158023,30981,2009-02-22 00:00:00,90.0,95.0,left,high,medium,81.0,...,20.0,79.0,20.0,20.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102505,102506,158023,30981,2008-08-30 00:00:00,90.0,95.0,left,high,medium,81.0,...,20.0,79.0,20.0,20.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102506,102507,158023,30981,2007-08-30 00:00:00,86.0,93.0,left,high,medium,83.0,...,20.0,79.0,20.0,20.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159
102507,102508,158023,30981,2007-02-22 00:00:00,85.0,94.0,left,high,medium,85.0,...,9.0,79.0,12.0,16.0,6176,Lionel Messi,158023,1987-06-24 00:00:00,170.18,159

In [18]:
Bale = df.loc[df['player_name'] == "Gareth Bale"]

In [19]:
Modric = df.loc[df['player_name'] == "Luka Modric"]

In [91]:
Umtiti = df.loc[df['player_name'] == "Samuel Umtiti"]
Umtiti

,id_x,player_fifa_api_id_x,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,player_name,player_fifa_api_id_y,birthday,height,weight
157299,157300,205600,210117,2016-04-07 00:00:00,80.0,85.0,left,high,high,64.0,...,10.0,14.0,12.0,15.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157300,157301,205600,210117,2016-03-31 00:00:00,80.0,86.0,left,high,high,64.0,...,10.0,14.0,12.0,15.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157301,157302,205600,210117,2016-02-04 00:00:00,79.0,85.0,left,high,high,64.0,...,10.0,14.0,12.0,15.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157302,157303,205600,210117,2015-11-12 00:00:00,79.0,85.0,left,high,high,64.0,...,10.0,14.0,12.0,15.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157303,157304,205600,210117,2015-09-21 00:00:00,79.0,85.0,left,high,high,64.0,...,10.0,14.0,12.0,15.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157304,157305,205600,210117,2015-05-15 00:00:00,77.0,83.0,left,high,medium,63.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157305,157306,205600,210117,2015-04-24 00:00:00,77.0,83.0,left,high,medium,63.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157306,157307,205600,210117,2015-04-10 00:00:00,77.0,83.0,left,high,medium,63.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157307,157308,205600,210117,2015-03-13 00:00:00,79.0,85.0,left,high,medium,63.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157308,157309,205600,210117,2015-02-20 00:00:00,78.0,84.0,left,high,medium,61.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157309,157310,205600,210117,2015-02-06 00:00:00,77.0,83.0,left,high,medium,61.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157310,157311,205600,210117,2015-01-09 00:00:00,77.0,83.0,left,high,medium,61.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157311,157312,205600,210117,2014-12-12 00:00:00,76.0,82.0,left,high,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157312,157313,205600,210117,2014-09-18 00:00:00,76.0,82.0,left,high,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157313,157314,205600,210117,2014-03-14 00:00:00,75.0,82.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157314,157315,205600,210117,2014-03-07 00:00:00,74.0,82.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157315,157316,205600,210117,2013-09-20 00:00:00,74.0,82.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157316,157317,205600,210117,2013-04-19 00:00:00,74.0,82.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157317,157318,205600,210117,2013-04-12 00:00:00,74.0,80.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157318,157319,205600,210117,2013-04-05 00:00:00,74.0,80.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157319,157320,205600,210117,2013-03-28 00:00:00,74.0,80.0,left,medium,medium,68.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157320,157321,205600,210117,2013-03-08 00:00:00,72.0,80.0,left,medium,medium,68.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157321,157322,205600,210117,2013-02-15 00:00:00,71.0,76.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157322,157323,205600,210117,2012-08-31 00:00:00,70.0,79.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157323,157324,205600,210117,2012-02-22 00:00:00,67.0,80.0,left,medium,medium,60.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157324,157325,205600,210117,2011-08-30 00:00:00,63.0,78.0,left,medium,medium,59.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165
157325,157326,205600,210117,2007-02-22 00:00:00,63.0,78.0,left,medium,medium,59.0,...,9.0,13.0,11.0,14.0,9456,Samuel Umtiti,205600,1993-11-14 00:00:00,180.34,165

In [21]:
Pogba = df.loc[df['player_name'] == "Presnel Kimpembe"]

In [22]:
Giroud = df.loc[df['player_name'] == "Olivier Giroud"]

In [92]:
Dembele = df.loc[df['player_name'] == "Ousmane Dembele"]
Dembele

,id_x,player_fifa_api_id_x,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,player_name,player_fifa_api_id_y,birthday,height,weight
137245,137246,231443,692984,2016-04-28 00:00:00,76.0,89.0,left,high,medium,67.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137246,137247,231443,692984,2016-04-14 00:00:00,75.0,88.0,left,high,medium,67.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137247,137248,231443,692984,2016-03-24 00:00:00,74.0,88.0,left,high,medium,67.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137248,137249,231443,692984,2016-03-17 00:00:00,74.0,88.0,right,high,medium,67.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137249,137250,231443,692984,2016-03-10 00:00:00,73.0,88.0,right,high,medium,60.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137250,137251,231443,692984,2016-03-03 00:00:00,70.0,87.0,right,high,medium,60.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137251,137252,231443,692984,2016-02-25 00:00:00,69.0,87.0,right,high,medium,60.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137252,137253,231443,692984,2016-02-18 00:00:00,68.0,86.0,right,high,medium,60.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137253,137254,231443,692984,2016-02-11 00:00:00,68.0,86.0,right,high,medium,60.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137254,137255,231443,692984,2016-02-04 00:00:00,65.0,83.0,right,high,medium,60.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137255,137256,231443,692984,2016-01-28 00:00:00,63.0,81.0,right,high,medium,54.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137256,137257,231443,692984,2016-01-21 00:00:00,62.0,80.0,right,medium,medium,53.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137257,137258,231443,692984,2016-01-14 00:00:00,62.0,80.0,right,medium,medium,52.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137258,137259,231443,692984,2015-11-06 00:00:00,57.0,75.0,right,medium,medium,50.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134
137259,137260,231443,692984,2007-02-22 00:00:00,57.0,75.0,right,medium,medium,50.0,...,6.0,14.0,10.0,13.0,8218,Ousmane Dembele,231443,1997-05-15 00:00:00,177.8,134

In [24]:
Varanne = df.loc[df['player_name'] == "Raphael Varane"]

In [25]:
Schweinsteiger = df.loc[df['player_name'] == "Bastian Schweinsteiger"]

In [26]:
Lewandowski = df.loc[df['player_name'] == "Robert Lewandowski"]

In [96]:
Mueller = df.loc[df['player_name'] == "Thomas Mueller"]
Mueller

,id_x,player_fifa_api_id_x,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,player_name,player_fifa_api_id_y,birthday,height,weight
170797,170798,189596,116772,2016-05-12 00:00:00,86.0,88.0,right,high,high,79.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170798,170799,189596,116772,2016-04-28 00:00:00,86.0,88.0,right,high,high,79.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170799,170800,189596,116772,2016-01-14 00:00:00,86.0,88.0,right,high,high,79.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170800,170801,189596,116772,2015-10-23 00:00:00,86.0,88.0,right,high,high,79.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170801,170802,189596,116772,2015-09-21 00:00:00,86.0,88.0,right,high,high,79.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170802,170803,189596,116772,2015-03-27 00:00:00,86.0,88.0,right,high,high,84.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170803,170804,189596,116772,2015-03-20 00:00:00,86.0,88.0,right,high,high,84.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170804,170805,189596,116772,2015-03-13 00:00:00,86.0,88.0,right,high,high,84.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170805,170806,189596,116772,2014-09-18 00:00:00,86.0,88.0,right,high,high,84.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170806,170807,189596,116772,2014-04-25 00:00:00,85.0,88.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170807,170808,189596,116772,2014-04-18 00:00:00,85.0,88.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170808,170809,189596,116772,2014-03-28 00:00:00,85.0,88.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170809,170810,189596,116772,2014-02-14 00:00:00,85.0,88.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170810,170811,189596,116772,2014-01-31 00:00:00,85.0,88.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170811,170812,189596,116772,2013-10-11 00:00:00,85.0,88.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170812,170813,189596,116772,2013-09-27 00:00:00,85.0,88.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170813,170814,189596,116772,2013-09-20 00:00:00,85.0,88.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170814,170815,189596,116772,2013-05-17 00:00:00,84.0,86.0,right,high,high,83.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170815,170816,189596,116772,2013-02-15 00:00:00,84.0,86.0,right,high,high,82.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170816,170817,189596,116772,2012-08-31 00:00:00,84.0,86.0,right,high,high,79.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170817,170818,189596,116772,2012-02-22 00:00:00,83.0,86.0,right,high,high,77.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170818,170819,189596,116772,2011-08-30 00:00:00,83.0,85.0,right,high,high,70.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170819,170820,189596,116772,2011-02-22 00:00:00,81.0,87.0,right,high,high,70.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170820,170821,189596,116772,2010-08-30 00:00:00,80.0,86.0,right,high,high,67.0,...,7.0,11.0,14.0,14.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170821,170822,189596,116772,2010-02-22 00:00:00,75.0,82.0,right,high,high,71.0,...,22.0,62.0,22.0,22.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170822,170823,189596,116772,2009-08-30 00:00:00,69.0,79.0,right,high,high,45.0,...,22.0,41.0,22.0,22.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170823,170824,189596,116772,2009-02-22 00:00:00,63.0,74.0,right,high,high,45.0,...,22.0,41.0,22.0,22.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170824,170825,189596,116772,2008-08-30 00:00:00,63.0,74.0,right,high,high,45.0,...,22.0,41.0,22.0,22.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165
170825,170826,189596,116772,2007-02-22 00:00:00,63.0,74.0,right,high,high,45.0,...,22.0,41.0,22.0,22.0,10243,Thomas Mueller,189596,1989-09-13 00:00:00,185.42,165

In [28]:
Ribery = df.loc[df['player_name'] == "Franck Ribery"]

In [95]:
Kane = df.loc[df['player_name'] == "Harry Kane"]
Kane

,id_x,player_fifa_api_id_x,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,player_name,player_fifa_api_id_y,birthday,height,weight
68957,68958,202126,194165,2016-04-28 00:00:00,82.0,88.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68958,68959,202126,194165,2016-04-21 00:00:00,81.0,87.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68959,68960,202126,194165,2016-01-28 00:00:00,81.0,87.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68960,68961,202126,194165,2015-12-24 00:00:00,80.0,86.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68961,68962,202126,194165,2015-12-10 00:00:00,80.0,86.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68962,68963,202126,194165,2015-12-03 00:00:00,79.0,85.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68963,68964,202126,194165,2015-11-26 00:00:00,79.0,85.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68964,68965,202126,194165,2015-11-19 00:00:00,79.0,85.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68965,68966,202126,194165,2015-10-30 00:00:00,79.0,85.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68966,68967,202126,194165,2015-10-23 00:00:00,79.0,85.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68967,68968,202126,194165,2015-09-25 00:00:00,78.0,84.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68968,68969,202126,194165,2015-09-21 00:00:00,78.0,84.0,right,high,high,69.0,...,10.0,11.0,14.0,11.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68969,68970,202126,194165,2015-05-29 00:00:00,78.0,84.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68970,68971,202126,194165,2015-05-01 00:00:00,78.0,84.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68971,68972,202126,194165,2015-04-10 00:00:00,78.0,84.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68972,68973,202126,194165,2015-03-13 00:00:00,77.0,84.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68973,68974,202126,194165,2015-02-20 00:00:00,77.0,84.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68974,68975,202126,194165,2015-02-06 00:00:00,76.0,82.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68975,68976,202126,194165,2015-01-23 00:00:00,75.0,81.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68976,68977,202126,194165,2015-01-09 00:00:00,75.0,81.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68977,68978,202126,194165,2014-12-19 00:00:00,75.0,81.0,right,high,high,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68978,68979,202126,194165,2014-12-12 00:00:00,74.0,80.0,right,high,medium,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68979,68980,202126,194165,2014-12-05 00:00:00,74.0,79.0,right,high,medium,69.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68980,68981,202126,194165,2014-11-14 00:00:00,73.0,79.0,right,high,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68981,68982,202126,194165,2014-11-07 00:00:00,72.0,80.0,right,high,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68982,68983,202126,194165,2014-10-31 00:00:00,72.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68983,68984,202126,194165,2014-09-18 00:00:00,71.0,78.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68984,68985,202126,194165,2014-04-11 00:00:00,68.0,74.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68985,68986,202126,194165,2014-03-21 00:00:00,67.0,74.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68986,68987,202126,194165,2014-02-28 00:00:00,67.0,74.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68987,68988,202126,194165,2014-02-14 00:00:00,67.0,74.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68988,68989,202126,194165,2013-12-27 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68989,68990,202126,194165,2013-11-08 00:00:00,68.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68990,68991,202126,194165,2013-09-20 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68991,68992,202126,194165,2013-07-12 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68992,68993,202126,194165,2013-06-07 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68993,68994,202126,194165,2013-05-31 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68994,68995,202126,194165,2013-03-22 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68995,68996,202126,194165,2013-03-01 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68996,68997,202126,194165,2013-02-22 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68997,68998,202126,194165,2013-02-15 00:00:00,67.0,80.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68998,68999,202126,194165,2012-08-31 00:00:00,67.0,79.0,right,medium,medium,57.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
68999,69000,202126,194165,2012-02-22 00:00:00,66.0,79.0,right,medium,medium,37.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
69000,69001,202126,194165,2011-08-30 00:00:00,62.0,72.0,right,medium,medium,37.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
69001,69002,202126,194165,2011-02-22 00:00:00,58.0,74.0,right,medium,medium,37.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143
69002,69003,202126,194165,2007-02-22 00:00:00,58.0,74.0,right,medium,medium,37.0,...,9.0,10.0,13.0,10.0,4142,Harry Kane,202126,1993-07-28 00:00:00,187.96,143

In [32]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

players = [Ronaldo, Ramos, Azpilicueta, Torres, DiMaria, Ibrahimovic, Beckham, Messi, Bale, Modric, Umtiti, Pogba, Giroud, Dembele, Varanne, Schweinsteiger, Lewandowski, Mueller, Ribery, Kane]

results = []
for player in players:
    X = player[[
       'overall_rating', 'potential', 'crossing', 'finishing', 'heading_accuracy',
       'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy',
       'long_passing', 'ball_control', 'acceleration', 'sprint_speed',
       'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina',
       'strength', 'long_shots', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle',
       'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning',
       'gk_reflexes', 'id_y', 'player_fifa_api_id_y',
        'height', 'weight']] # player data
    y = player["overall_rating"] # target variable
    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the model
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)
    y_pred


    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score

    # Mean Absolute Error
    mae = mean_absolute_error(y_test, y_pred)
    print(f'Mean Absolute Error ', mae)

    # Mean Squared Error
    mse = mean_squared_error(y_test, y_pred)
    print(f'Mean Squared Error ', mse)
    
    # R-squared
    r2 = r2_score(y_test, y_pred)
    print(f'R-squared ', r2)

Mean Absolute Error  0.18400000000000033
Mean Squared Error  0.06964000000000083
R-squared  0.825899999999998
Mean Absolute Error  0.30749999999999744
Mean Squared Error  0.22897499999999887
R-squared  0.8473500000000007
Mean Absolute Error  0.7900000000000004
Mean Squared Error  1.436566666666665
R-squared  0.9761125173210162
Mean Absolute Error  0.3357142857142849
Mean Squared Error  0.1708428571428557
R-squared  0.9755225146198833
Mean Absolute Error  0.5933333333333314
Mean Squared Error  1.0106333333333313
R-squared  0.9619824451410659
Mean Absolute Error  0.29399999999999693
Mean Squared Error  0.10457999999999842
R-squared  0.34637500000000987
Mean Absolute Error  0.36999999999999506
Mean Squared Error  0.25636666666666247
R-squared  0.9112576923076938
Mean Absolute Error  0.6166666666666671
Mean Squared Error  1.321699999999997
R-squared  0.8460155339805828
Mean Absolute Error  0.595714285714286
Mean Squared Error  0.711414285714285
R-squared  0.9768222739361703
Mean Absolute Error  0.3039999999999992
Mean Squared Error  0.1540400000000014
R-squared  0.9416515151515146
Mean Absolute Error  0.8933333333333332
Mean Squared Error  1.0237666666666654
R-squared  0.8464350000000002
Mean Absolute Error  2.0
Mean Squared Error  5.0
R-squared  -4.0
Mean Absolute Error  0.7650000000000023
Mean Squared Error  1.9530500000000024
R-squared  0.9703802843601895
Mean Absolute Error  0.7366666666666669
Mean Squared Error  0.836833333333331
R-squared  0.9768972392638038
Mean Absolute Error  0.6125000000000007
Mean Squared Error  0.8598250000000024
R-squared  -0.7196500000000048
Mean Absolute Error  0.2049999999999983
Mean Squared Error  0.1343833333333331
R-squared  0.9792369098712447
Mean Absolute Error  0.47285714285714114
Mean Squared Error  0.6195857142857123
R-squared  0.9896170656634747
Mean Absolute Error  0.3750000000000024
Mean Squared Error  0.40381666666666977
R-squared  0.9938944141117177
Mean Absolute Error  0.2420000000000016
Mean Squared Error  0.13366000000000233
R-squared  0.9582312499999993
Mean Absolute Error  0.418
Mean Squared Error  0.4740600000000006
R-squared  0.9902235512476799

In [33]:
team_data

        id  team_api_id  team_fifa_api_id      team_long_name team_short_name
0        1         9987             673.0            KRC Genk             GEN
1        2         9993             675.0        Beerschot AC             BAC
2        3        10000           15005.0    SV Zulte-Waregem             ZUL
3        4         9994            2007.0    Sporting Lokeren             LOK
4        5         9984            1750.0   KSV Cercle Brugge             CEB
..     ...          ...               ...                 ...             ...
294  49479        10190             898.0       FC St. Gallen             GAL
295  49837        10191            1715.0             FC Thun             THU
296  50201         9777             324.0         Servette FC             SER
297  50204         7730            1862.0  FC Lausanne-Sports             LAU
298  51606         7896               NaN              Lugano             LUG

[299 rows x 5 columns]

In [34]:
team_attributes

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,1454,15005,10000,2011-02-22 00:00:00,52,Balanced,NaN,Little,52,Mixed,...,53,Normal,Organised,46,Medium,48,Press,53,Normal,Cover
1454,1455,15005,10000,2012-02-22 00:00:00,54,Balanced,NaN,Little,51,Mixed,...,50,Normal,Organised,44,Medium,55,Press,53,Normal,Cover
1455,1456,15005,10000,2013-09-20 00:00:00,54,Balanced,NaN,Little,51,Mixed,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1456,1457,15005,10000,2014-09-19 00:00:00,54,Balanced,42.0,Normal,51,Mixed,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover
1457,1458,15005,10000,2015-09-10 00:00:00,54,Balanced,42.0,Normal,51,Mixed,...,32,Little,Organised,44,Medium,58,Press,37,Normal,Cover

In [52]:
df2 = pd.merge(team_attributes, team_data, on="team_api_id", how="inner")
df2 = df2.drop(["id_x", 'buildUpPlaySpeedClass', 'buildUpPlayDribblingClass', 'buildUpPlayPassingClass', 'buildUpPlayPositioningClass',
        'chanceCreationPassingClass','chanceCreationCrossingClass','chanceCreationShootingClass','chanceCreationPositioningClass', 'defencePressureClass', 'defenceAggressionClass',
        'defenceTeamWidthClass', 'defenceDefenderLineClass', 'id_y', 'team_fifa_api_id_y'], axis=1)
df2

,team_fifa_api_id_x,team_api_id,date,buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth,team_long_name,team_short_name
0,434,9930,2010-02-22 00:00:00,60,NaN,50,60,65,55,50,55,45,FC Aarau,AAR
1,434,9930,2014-09-19 00:00:00,52,48.0,56,54,63,64,47,44,54,FC Aarau,AAR
2,434,9930,2015-09-10 00:00:00,47,41.0,54,54,63,64,47,44,54,FC Aarau,AAR
3,77,8485,2010-02-22 00:00:00,70,NaN,70,70,70,70,60,70,70,Aberdeen,ABE
4,77,8485,2011-02-22 00:00:00,47,NaN,52,53,48,52,47,47,52,Aberdeen,ABE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1453,15005,10000,2011-02-22 00:00:00,52,NaN,52,52,48,53,46,48,53,SV Zulte-Waregem,ZUL
1454,15005,10000,2012-02-22 00:00:00,54,NaN,51,47,52,50,44,55,53,SV Zulte-Waregem,ZUL
1455,15005,10000,2013-09-20 00:00:00,54,NaN,51,47,52,32,44,58,37,SV Zulte-Waregem,ZUL
1456,15005,10000,2014-09-19 00:00:00,54,42.0,51,47,52,32,44,58,37,SV Zulte-Waregem,ZUL
1457,15005,10000,2015-09-10 00:00:00,54,42.0,51,47,52,32,44,58,37,SV Zulte-Waregem,ZUL

In [55]:
Barcelona = df2.loc[df2['team_long_name'] == "FC Barcelona"]
Barcelona

,team_fifa_api_id_x,team_api_id,date,buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth,team_long_name,team_short_name
118,241,8634,2010-02-22 00:00:00,42,NaN,30,65,40,70,70,30,70,FC Barcelona,BAR
119,241,8634,2011-02-22 00:00:00,43,NaN,34,59,25,68,67,43,68,FC Barcelona,BAR
120,241,8634,2012-02-22 00:00:00,24,NaN,25,37,24,54,66,63,66,FC Barcelona,BAR
121,241,8634,2013-09-20 00:00:00,35,NaN,32,37,31,35,61,63,65,FC Barcelona,BAR
122,241,8634,2014-09-19 00:00:00,35,35.0,32,37,31,35,61,63,65,FC Barcelona,BAR
123,241,8634,2015-09-10 00:00:00,36,35.0,51,36,49,56,61,65,65,FC Barcelona,BAR

In [60]:
Real_Madrid = df2.loc[df2['team_long_name'] == "Real Madrid CF"]
Real_Madrid

,team_fifa_api_id_x,team_api_id,date,buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth,team_long_name,team_short_name
1048,243,8633,2010-02-22 00:00:00,55,NaN,30,70,60,70,65,40,65,Real Madrid CF,REA
1049,243,8633,2011-02-22 00:00:00,54,NaN,39,67,60,67,68,55,55,Real Madrid CF,REA
1050,243,8633,2012-02-22 00:00:00,45,NaN,35,71,54,73,49,60,68,Real Madrid CF,REA
1051,243,8633,2013-09-20 00:00:00,50,NaN,41,68,54,72,39,49,65,Real Madrid CF,REA
1052,243,8633,2014-09-19 00:00:00,50,54.0,41,68,54,69,39,49,65,Real Madrid CF,REA
1053,243,8633,2015-09-10 00:00:00,50,57.0,46,61,41,63,52,60,63,Real Madrid CF,REA

In [89]:
Chelsea = df2.loc[df2['team_long_name'] == "Chelsea"] #AZPILICUETA
Chelsea = Chelsea.fillna(0)
Chelsea

,team_fifa_api_id_x,team_api_id,date,buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth,team_long_name,team_short_name
306,5,8455,2010-02-22 00:00:00,70,0.0,60,56,70,70,30,60,35,Chelsea,CHE
307,5,8455,2011-02-22 00:00:00,60,0.0,50,60,60,80,35,55,50,Chelsea,CHE
308,5,8455,2012-02-22 00:00:00,60,0.0,45,55,45,45,60,62,46,Chelsea,CHE
309,5,8455,2013-09-20 00:00:00,46,0.0,41,46,61,63,42,43,46,Chelsea,CHE
310,5,8455,2014-09-19 00:00:00,67,52.0,38,41,61,68,39,41,46,Chelsea,CHE
311,5,8455,2015-09-10 00:00:00,67,41.0,36,41,34,44,39,41,46,Chelsea,CHE

In [88]:
Marseille = df2.loc[df2['team_long_name'] == "Olympique de Marseille"] #AZPILICUETA
Marseille = Marseille.fillna(0)
Marseille

,team_fifa_api_id_x,team_api_id,date,buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth,team_long_name,team_short_name
818,219,8592,2010-02-22 00:00:00,55,0.0,45,70,65,70,65,70,65,Olympique de Marseille,MAR
819,219,8592,2011-02-22 00:00:00,65,0.0,35,65,65,80,55,55,65,Olympique de Marseille,MAR
820,219,8592,2012-02-22 00:00:00,48,0.0,50,49,51,48,44,48,51,Olympique de Marseille,MAR
821,219,8592,2013-09-20 00:00:00,48,0.0,50,49,77,64,44,48,54,Olympique de Marseille,MAR
822,219,8592,2014-09-19 00:00:00,51,62.0,50,49,69,68,48,48,60,Olympique de Marseille,MAR
823,219,8592,2015-09-10 00:00:00,51,77.0,41,49,69,31,48,48,60,Olympique de Marseille,MAR

In [83]:
Chelsea.columns

Index(['team_fifa_api_id_x', 'team_api_id', 'date', 'buildUpPlaySpeed',
       'buildUpPlayDribbling', 'buildUpPlayPassing', 'chanceCreationPassing',
       'chanceCreationCrossing', 'chanceCreationShooting', 'defencePressure',
       'defenceAggression', 'defenceTeamWidth', 'team_long_name',
       'team_short_name'],
      dtype='object')

In [90]:
# AZPILICUETA

import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

teams = [Chelsea, Marseille]

results = []
for team in teams:
    X = team[[
       'team_fifa_api_id_x', 'team_api_id', 
       'buildUpPlayDribbling', 'buildUpPlayPassing', 'chanceCreationPassing',
       'chanceCreationCrossing', 'chanceCreationShooting', 'defencePressure',
       'defenceAggression', 'defenceTeamWidth',
       ]] # team data
    y = team['buildUpPlaySpeed'] # target variable
    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the model
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)
    y_pred


    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score

    # Mean Absolute Error
    mae = mean_absolute_error(y_test, y_pred)
    print(f'Mean Absolute Error ', mae)

    # Mean Squared Error
    mse = mean_squared_error(y_test, y_pred)
    print(f'Mean Squared Error ', mse)
    
    # R-squared
    r2 = r2_score(y_test, y_pred)
    print(f'R-squared ', r2)

Mean Absolute Error  10.530000000000001
Mean Squared Error  135.88090000000003
R-squared  -4.435236000000001
Mean Absolute Error  9.899999999999999
Mean Squared Error  123.00999999999998
R-squared  -3.920399999999999